### ISSUE TITLE
error messages on container shutdown

### ISSUE THREAD

**Issue by cybermcm** [crazy-max/docker-fail2ban#101]
#### Steps to reproduce this issue

shut down container

#### Expected behaviour

clean shutdown

#### Actual behaviour

error messages probably due to config in this thread?
https://github.com/crazy-max/docker-fail2ban/issues/29
container and bans seem to work although there are errors on shutdown

### Configuration

* Docker version: `Docker version 20.10.8`
* Docker compose version: `docker-compose version 1.29.2`
* Platform: `Debian 11.0`
* System info: `Linux s01 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux`
* Include all necessary configuration files :
docker-compose.yml:
```
fail2ban:
  cap_add:
   - NET_ADMIN
   - NET_RAW
  container_name: fail2ban
  depends_on:
   - mail
  environment:
   - TZ=${TZ}
   - F2B_LOG_TARGET=STDOUT
   - F2B_LOG_LEVEL=INFO
   - F2B_DB_PURGE_AGE=1d
   - SSMTP_HOST=${SMTP_HOST}
   - SSMTP_PORT=${SMTP_PORT}
   - SSMTP_HOSTNAME=${HOSTNAME}
   - SSMTP_USER=${SMTP_USER}
   - SSMTP_PASSWORD=${SMTP_PASSWORD}
   - SSMTP_TLS=YES
   - SSMTP_STARTTLS=YES
  image: ghcr.io/crazy-max/fail2ban
  labels:
   - ${WATCHTOWER_TRUE}
  logging:
   driver: loki
   options:
    loki-url: http://localhost:3100/loki/api/v1/push
  network_mode: "host"
  restart: always
  volumes:
   #- ${TIMEZONE}
   #- ${LOCALTIME}
   - ${DOCKER_PATH}/fail2ban:/data
   - ${WORKING_PATH}/_log:/opt/log:ro
   - ${DOCKER_PATH}/bitwarden:/opt/bitwarden:ro
   - ${DOCKER_PATH}/heimdall/log/nginx:/opt/docker/heimdall/log/nginx:ro
   - ${DOCKER_PATH}/mail/log/mail.log:/opt/docker/mail/log/mail.log:ro
   - /var/log:/opt/log_host:ro
```

### Docker info

```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 75
  Running: 75
  Paused: 0
  Stopped: 0
 Images: 82
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-8-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 17.58GiB
 Name: s01
 ID: YA4F:BBYX:HZ2D:33E7:SXJP:MZ6P:SBBQ:VH3N:66X7:I5FT:AF3M:C4AS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: cybermcm
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.1:2345
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

### Logs

```
2021-09-22 07:49:54 | 2021-09-22 07:49:54,336 fail2ban.server         [1]: INFO    Exiting Fail2ban
-- | --
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,335 fail2ban.database       [1]: INFO    Connection to database closed.
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,334 fail2ban.jail           [1]: INFO    Jail 'sasl' stopped
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,334 fail2ban.jail           [1]: INFO    Jail 'phpmyadmin' stopped
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,333 fail2ban.jail           [1]: INFO    Jail 'heimdall' stopped
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,133 fail2ban.jail           [1]: INFO    Jail 'code' stopped
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,133 fail2ban.jail           [1]: INFO    Jail 'bitwarden-admin' stopped
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,132 fail2ban.jail           [1]: INFO    Jail 'traefik-auth' stopped
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,132 fail2ban.jail           [1]: INFO    Jail 'bitwarden' stopped
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,132 fail2ban.jail           [1]: INFO    Jail 'dovecot' stopped
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,132 fail2ban.jail           [1]: INFO    Jail 'postfix' stopped
  |   | 2021-09-22 07:49:54 | AttributeError: 'Actions' object has no attribute '_logSys'
  |   | 2021-09-22 07:49:54 | self._logSys.error("Invariant check failed. Flush is impossible.")
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/actions.py", line 663, in _beforeRepair
  |   | 2021-09-22 07:49:54 | if beforeRepair and not beforeRepair():
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/action.py", line 916, in _invariantCheck
  |   | 2021-09-22 07:49:54 | if started and not self._invariantCheck(family, beforeRepair):
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/action.py", line 690, in consistencyCheck
  |   | 2021-09-22 07:49:54 | action.consistencyCheck(_beforeRepair)
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/actions.py", line 666, in __flushBan
  |   | 2021-09-22 07:49:54 | self.__flushBan(stop=True)
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/actions.py", line 368, in run
  |   | 2021-09-22 07:49:54 | run(*args, **kwargs)
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/jailthread.py", line 69, in run_with_except_hook
  |   | 2021-09-22 07:49:54 | Traceback (most recent call last):
  |   | 2021-09-22 07:49:54 | During handling of the above exception, another exception occurred:
  |   | 2021-09-22 07:49:54 | RuntimeError: Error flushing action Jail('postfix')/nftables-forward: 'Script error'
  |   | 2021-09-22 07:49:54 | raise RuntimeError("Error %s action %s/%s: %r" % (operation, self._jail, self._name, err))
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/action.py", line 476, in _executeOperation
  |   | 2021-09-22 07:49:54 | return self._executeOperation('<actionflush>', 'flushing', family=family, afterExec=_afterFlush)
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/action.py", line 637, in flush
  |   | 2021-09-22 07:49:54 | if action.flush():
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/actions.py", line 653, in __flushBan
  |   | 2021-09-22 07:49:54 | Traceback (most recent call last):
  |   | 2021-09-22 07:49:54 | AttributeError: 'Actions' object has no attribute '_logSys'
  |   | 2021-09-22 07:49:54 | self._logSys.error("Invariant check failed. Flush is impossible.")
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/actions.py", line 663, in _beforeRepair
  |   | 2021-09-22 07:49:54 | if beforeRepair and not beforeRepair():
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/action.py", line 916, in _invariantCheck
  |   | 2021-09-22 07:49:54 | if started and not self._invariantCheck(family, beforeRepair):
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/action.py", line 690, in consistencyCheck
  |   | 2021-09-22 07:49:54 | action.consistencyCheck(_beforeRepair)
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/actions.py", line 666, in __flushBan
  |   | 2021-09-22 07:49:54 | self.__flushBan(stop=True)
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/actions.py", line 368, in run
  |   | 2021-09-22 07:49:54 | run(*args, **kwargs)
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/jailthread.py", line 69, in run_with_except_hook
  |   | 2021-09-22 07:49:54 | Traceback (most recent call last):
  |   | 2021-09-22 07:49:54 | During handling of the above exception, another exception occurred:
  |   | 2021-09-22 07:49:54 | RuntimeError: Error flushing action Jail('postfix')/nftables-forward: 'Script error'
  |   | 2021-09-22 07:49:54 | raise RuntimeError("Error %s action %s/%s: %r" % (operation, self._jail, self._name, err))
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/action.py", line 476, in _executeOperation
  |   | 2021-09-22 07:49:54 | return self._executeOperation('<actionflush>', 'flushing', family=family, afterExec=_afterFlush)
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/action.py", line 637, in flush
  |   | 2021-09-22 07:49:54 | if action.flush():
  |   | 2021-09-22 07:49:54 | File "/usr/lib/python3.9/site-packages/fail2ban/server/actions.py", line 653, in __flushBan
  |   | 2021-09-22 07:49:54 | Traceback (most recent call last):
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,125 fail2ban                [1]: CRITICAL Unhandled exception in Fail2Ban:
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,125 fail2ban.utils          [1]: ERROR   7fc113c0d030 -- returned 1
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,125 fail2ban.utils          [1]: ERROR   7fc113c0d030 -- stderr: '                ^^^^^^^^^'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,125 fail2ban.utils          [1]: ERROR   7fc113c0d030 -- stderr: 'list chain inet f2b-table f2b-chain-forward'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,125 fail2ban.utils          [1]: ERROR   7fc113c0d030 -- stderr: 'Error: No such file or directory'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,125 fail2ban.utils          [1]: ERROR   7fc113c0d030 -- exec: nft list chain inet f2b-table f2b-chain-forward \| grep -q '@addr-set-postfix[ \t]'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,113 fail2ban.actions        [1]: INFO    No flush occurred, do consistency check
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,113 fail2ban.actions        [1]: ERROR   Failed to flush bans in jail 'postfix' action 'nftables-forward': Error flushing action Jail('postfix')/nftables-forward: 'Script error'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- returned 1
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '              ^^^^^^^^^'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'add rule inet f2b-table f2b-chain-forward tcp dport { submission,smtps,pop3,pop3s,imap,imaps } ip saddr @addr-set-postfix reject'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'Error: No such file or directory'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '              ^^^^^^^^^'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'add rule inet f2b-table f2b-chain-forward tcp dport { submission,smtps,pop3,pop3s,imap,imaps } ip saddr @addr-set-postfix reject'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'Error: No such file or directory'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '             ^^^^^^^^^'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'add set inet f2b-table addr-set-postfix { type ipv4_addr; }'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'Error: No such file or directory'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '                ^^^^^^^^^'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'delete set inet f2b-table addr-set-postfix'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'Error: Could not process rule: No such file or directory'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,112 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '                ^^^^^^^^^'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'list chain inet f2b-table f2b-chain-forward'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'Error: No such file or directory'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-f FILE\tRead pattern from file'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-e PTRN\tPattern to match'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: "\t-C N\tSame as '-A N -B N'"
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-B N\tPrint N lines of leading context'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-A N\tPrint N lines of trailing context'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-m N\tMatch up to N times per file'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-E\tPATTERN is an extended regexp'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-F\tPATTERN is a literal (not regexp)'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-x\tMatch whole lines only'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-w\tMatch whole words only'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-i\tIgnore case'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,111 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-R\tRecurse and dereference symlinks'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,110 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-r\tRecurse'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,110 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-s\tSuppress open and read errors'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,110 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-v\tSelect non-matching lines'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,110 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-q\tQuiet. Return 0 if PATTERN is found, 1 otherwise'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,110 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-o\tShow only the matching part of line'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,110 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-c\tShow only count of matching lines'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,110 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: "\t-L\tShow only names of files that don't match"
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,110 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: '\t-l\tShow only names of files that match'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,110 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: "\t-n\tAdd 'line_no:' prefix"
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,110 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: "\t-h\tDo not add 'filename:' prefix"
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,110 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: "\t-H\tAdd 'filename:' prefix"
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,109 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: ''
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,109 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'Search for PATTERN in FILEs (or stdin)'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,109 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: ''
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,109 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'Usage: grep [-HhnlLoqvsrRiwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,109 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: ''
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,109 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'BusyBox v1.33.1 () multi-call binary.'
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,109 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- stderr: 'grep: unrecognized option: P'
  |   | 2021-09-22 07:49:54 | }
  |   | 2021-09-22 07:49:54 | done
  |   | 2021-09-22 07:49:54 | nft add rule inet f2b-table f2b-chain-forward $proto dport \{ $(echo 'submission,smtps,pop3,pop3s,imap,imaps' \| sed s/:/-/g) \} ip saddr @addr-set-postfix reject
  |   | 2021-09-22 07:49:54 | for proto in $(echo 'tcp' \| sed 's/,/ /g'); do
  |   | 2021-09-22 07:49:54 | nft add set inet f2b-table addr-set-postfix \{ type ipv4_addr\; \}
  |   | 2021-09-22 07:49:54 | nft delete set inet f2b-table addr-set-postfix
  |   | 2021-09-22 07:49:54 | nft delete rule inet f2b-table f2b-chain-forward $hdl; done
  |   | 2021-09-22 07:49:54 | { nft -a list chain inet f2b-table f2b-chain-forward \| grep -oP '@addr-set-postfix\s+.*\s+\Khandle\s+(\d+); } \| while read -r hdl; do
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,109 fail2ban.utils          [1]: ERROR   7fc1141764a0 -- exec: { nft flush set inet f2b-table addr-set-postfix 2> /dev/null; } \|\| {
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,050 fail2ban.jail           [1]: INFO    Jail 'sshd' stopped
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,020 fail2ban.actions        [1]: NOTICE  [postfix] Flush ticket(s) with nftables-forward
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,016 fail2ban.actions        [1]: NOTICE  [phpmyadmin] Flush ticket(s) with nftables-forward
  |   | 2021-09-22 07:49:54 | 2021-09-22 07:49:54,015 fail2ban.actions        [1]: NOTICE  [sasl] Flush ticket(s) with nftables-forward
```

**Comment by cybermcm** [comment]
wow, that was really fast, can confirm, no more errors on container shutdown, thanks
